//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "First Name is Requierd.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Please enter valid Name.")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last Name is Requierd.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Please enter valid Name.")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Job Description is Requierd.")]
        [RegularExpression(@"^[a-zA-Z0-9 ]+$", ErrorMessage = "Please enter valid Description.")]
        public string JobDescription { get; set; }
        [Required(ErrorMessage = "Mobile is Requierd.")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Please enter valid Mobile Number.")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "Email is Requierd.")]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3]\.)|(([\w-]+\.)+))([a-zA-Z{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter valid Email.")]
        public string Email { get; set; }

        public byte[] Photo { get; set; }
        [Required(ErrorMessage = "UserName is Requierd.")]
        [RegularExpression(@"^[a-zA-Z0-9_]+$", ErrorMessage = "Please enter valid UserName.")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Password is Requierd.")]
        public string Password { get; set; }

        public Nullable<int> UserType { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
